# This file was generated by the {rix} R package v0.15.7 on 2025-04-18
# with following call:
# >rix::rix(r_ver = "4.5.0",
#  > r_pkgs = c("glue"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "positron",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-04-16.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      glue;
  };
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      positron-bin
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
